[package]
name = "qtrace-provider"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
hex.workspace = true
lz4_flex = { version = "0.11", features = ["frame"] }
serde.workspace = true
twox-hash.workspace = true

[dev-dependencies]
proptest.workspace = true
serde_json.workspace = true
sha2.workspace = true
