[package]
name = "qtrace-store"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
getrandom = "0.3"
hex.workspace = true
object = { version = "0.37", default-features = false, features = ["elf", "read_core", "std"] }
qtrace-provider = { path = "../qtrace-provider", version = "0.1.0" }
rusqlite = { version = "0.37", features = ["bundled"] }
rustix = { version = "1.1", features = ["fs", "process"] }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true

[dev-dependencies]
lz4_flex = { version = "0.11", features = ["frame"] }
rustix = { version = "1.1", features = ["process"] }
tempfile.workspace = true
